<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['user_dropbox_app_description'] = 'Dropbox is a cloud-based file storage and synchronization service.  Use this app to synchronize files to a folder located in your home directory which can then be accessed by any device associated to the same Dropbox account (laptop, mobile, tablet etc.).';
$lang['user_dropbox_app_name'] = 'Dropbox';
$lang['user_dropbox_authenticate_to_service'] = 'Authenticate with Dropbox';
$lang['user_dropbox_authentication'] = 'Complete setup by authenticating with Dropbox';
$lang['user_dropbox_create_account'] = 'Create Dropbox account';
$lang['user_dropbox_have_account'] = 'I already have a Dropbox account';
$lang['user_dropbox_init_complete'] = 'Initialization complete.  Please click on the link below to complete Dropbox authorization to your account.';
$lang['user_dropbox_initialize_dropbox_setup_help'] = 'You will need a Dropbox account to synchronize your local server folder to the cloud-based service.';
$lang['user_dropbox_initialize_dropbox_sync_help'] = 'Now that you have your Dropbox account setup, click on the "Synchronize Now" button.  You will be provided with a URL containing a key to the Dropbox folder residing in your home directory.  Use this link to associate your Dropbox account with this destination by clicking on it and completing the Dropbox authorization.';
$lang['user_dropbox_invalid_account'] = 'Account is invalid.';
$lang['user_dropbox_not_available_for_root_account'] = 'Sorry, the Dropbox service is not available for the root account.';
$lang['user_dropbox_starting_account_init'] = 'Starting account initialization... please be patient.';
$lang['user_dropbox_step_1'] = 'Step 1 of 2';
$lang['user_dropbox_step_2'] = 'Step 2 of 2';
$lang['user_dropbox_sync_now'] = 'Synchronize Now';
$lang['user_dropbox_url_link'] = 'Dropbox URL Link';
$lang['user_dropbox_waiting_confirmation'] = 'Waiting for Dropbox account synchronization authentication to complete.  Please click on the Dropbox URL Link below if you have not visited the Dropbox site and linked your account.';
