<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['user_dropbox_app_description'] = 'Dropbox jest chmurowym magazynem plików oraz usługą synchronizacji.  Korzystaj z tej aplikacji aby synchronizować pliki do folderu znajdującego się w Twoim katalogu domowy, do którego następnie można uzyskać dostęp z każdego urządzenia powiązanego z tym samym kontem Dropbox (laptop, telefon, tablet, itd.).';
$lang['user_dropbox_app_name'] = 'Dropbox';
$lang['user_dropbox_authenticate_to_service'] = 'Uwierzytelnij przez Dropbox';
$lang['user_dropbox_authentication'] = 'Zakończ ustawienia uwierzytelniając przez Dropbox';
$lang['user_dropbox_create_account'] = 'Utwórz konto Dropbox';
$lang['user_dropbox_have_account'] = 'Już posiadam konto Dropbox';
$lang['user_dropbox_init_complete'] = 'Inicjalizacja zakończona.  Proszę kliknąć w poniższy link aby zakończyć uwierzytelnianie Dropbox z Twoim kontem.';
$lang['user_dropbox_initialize_dropbox_setup_help'] = 'Będziesz potrzebować konta Dropbox aby synchronizować Twój lokalny folder na serwerze z usługą chmurową.';
$lang['user_dropbox_initialize_dropbox_sync_help'] = 'Teraz kiedy już masz konto Dropbox, kliknij w przycisk "Synchronizuj teraz".  Zobaczysz wtedy URL zawierający klucz do foldera Dropbox mieszczący się w Twoim katalogu domowym.  Użyj tego linka aby powiązać swoje konto Dropbox z tą lokalizacją klikając na niego i dokonując uwierzytelniania z kontem Dropbox.';
$lang['user_dropbox_invalid_account'] = 'Konto jest nieprawidłowe.';
$lang['user_dropbox_not_available_for_root_account'] = 'Przepraszamy, Usługa Dropbox nie jest dostępna dla konta root.';
$lang['user_dropbox_starting_account_init'] = 'Rozpoczynam inicjalizację konta... proszę o cierpliwość.';
$lang['user_dropbox_step_1'] = 'Krok 1 z 2';
$lang['user_dropbox_step_2'] = 'Krok 2 z 2';
$lang['user_dropbox_sync_check'] = 'Check Sync';
$lang['user_dropbox_sync_now'] = 'Synchronizuj teraz';
$lang['user_dropbox_url_link'] = 'Link URL do Dropbox';
$lang['user_dropbox_waiting_confirmation'] = 'Oczekiwania na uwierzytelnienie synchronizacji konta Dropbox zostało zakończone.  Proszę kliknąć w link URL do Dropbox znajdujący się poniżej, jeżeli nie odwiedziłeś jeszcze strony Dropbox w celu połączenia swoich kont.';
